server:
  port: 8989

template:
  project: 10369 #전자문서사업부_프로젝트_템플릿
  maintenance: 10370 #전자문서사업부_유지보수_템플릿

spring:
  datasource:
    url: jdbc:sqlserver://192.168.4.125:1433;databaseName=maedp;encrypt=false
    username: markany
    password: markany
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.SQL: debug


jwt:
  secret: cbc4f321d01c9ada7a803427d35a10b9d9743d34dbb723c1e56b88e1d8a7deac


전자문서사업부 :
  직원: 안용찬, 김은희, 이현진, 안혜진, 한경희, 최진혁, 최완주, 송명규, 임선정, 김선근, 강인환, 김태헌, 최수현, 이호섭, 이선민, 황희원, 최정오, 강창주, 김태호, 김찬호, epage div, 심혜경, 박수지, 홍현정, 송인찬, 김민수, 송화영, 정세미
