name: Gradle Package

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 실행
  release:
    types: [created]

jobs:
  build:
    runs-on: self-hosted  # 로컬에서 실행될 self-hosted runner 사용
    permissions:
      contents: read
      packages: write

    steps:
      # 소스 코드 체크 아웃
      - uses: actions/checkout@v4

      # JDK 11 설치
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Gradle로 프로젝트 빌드 (JAR 파일 생성)
      - name: Build with Gradle
        run: ./gradlew build

      # 빌드된 JAR 파일을 WSL Ubuntu-22.04 서버로 복사
      - name: Copy JAR to WSL Ubuntu-22.04
        run: |
          scp -o StrictHostKeyChecking=no -r ./build/libs/Data-Transfer-Engine.jar root@192.168.219.143:/home/test/app/

      # WSL Ubuntu에서 Docker 이미지 빌드 및 기존 컨테이너 교체
      - name: Build and Replace Docker Container on WSL
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 root@192.168.219.143 << EOF
          cd /home/test/app/
          
          docker stop data-transfer-engine || true
          docker rm data-transfer-engine || true
          
          docker build -t data-transfer-engine:latest .
          
          docker run -d --name data-transfer-engine -p 8888:8888 data-transfer-engine:latest
          EOF
