name: Gradle Package

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 실행
  release:
    types: [created]

jobs:
  build:
    runs-on: self-hosted  # 로컬에서 실행될 self-hosted runner 사용
    permissions:
      contents: read
      packages: write

    steps:
      # 소스 코드 체크 아웃
      - uses: actions/checkout@v4

      # JDK 11 설치
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Gradle로 프로젝트 빌드 (JAR 파일 생성)
      - name: Build with Gradle
        run: ./gradlew build

      # JAR 파일 압축
      - name: Compress files before SCP
        run: tar -czvf Data-Transfer-Engine.tar.gz ./build/libs/Data-Transfer-Engine.jar

      # 압축 파일을 서버에 전송
      - name: Copy compressed file to server
        run: scp -o StrictHostKeyChecking=no -r Data-Transfer-Engine.tar.gz root@192.168.219.143:/home/test/app/

      # 서버에서 압축 파일 해제
      - name: Extract files on server
        run: ssh root@192.168.219.143 'tar -xzvf /home/test/app/Data-Transfer-Engine.tar.gz -C /home/test/app/'

      # WSL Ubuntu에서 Docker 이미지 빌드 및 기존 컨테이너 교체
      - name: Build and Replace Docker Container on WSL
        run: |
          ssh -o StrictHostKeyChecking=no root@192.168.219.143 << EOF
          cd /home/test/app/
          
          if docker ps -a --format '{{.Names}}' | grep -Eq "^data-transfer-engine\$"; then
            docker stop data-transfer-engine
            docker rm data-transfer-engine
          fi
          
          docker build -t data-transfer-engine:latest .
          
          docker run -d --name data-transfer-engine -p 8888:8888 data-transfer-engine:latest
          EOF
